ALTER TABLE episodes ADD COLUMN IF NOT EXISTS homepage_featured BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS promo_links JSONB;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS quote TEXT;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS additional_photos JSONB;

CREATE TABLE IF NOT EXISTS site_settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT ''
);
