export type Show = 'Life Between Titles' | 'Work Unscripted' | 'Office Hours'

export interface Episode {
  videoNumber?: number
  show: Show
  season: number
  episode?: number
  guest: string
  youtubeTitle: string
  description: string
  mainTags: string
  tags: string
  resources: string
  status: 'Published' | 'Recorded' | 'Scheduled' | 'Reached Out' | 'To Be Planned'
}

export const EPISODES: Episode[] = [
  {
    videoNumber: 5,
    show: 'Life Between Titles',
    season: 1,
    episode: 5,
    guest: 'Phil Reiman',
    youtubeTitle: '25 Years Inside the Pentagon. Now What?',
    description: 'He spent 25 years inside the Department of Defense as a lawyer. He loved every minute of it. Now he\'s in the in-between, figuring out what a career that long leaves behind and what it points toward. This is a conversation about the weight of expertise, the strangeness of stopping, and what comes next when the thing that defined you is done.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#governmentcareer',
    resources: '📄 Teal AI résumé tool → https://get.tealhq.com/zzNxQ7 | 🧠 Free anxiety assessment → https://go.online-therapy.com/SHwO | 📓 Guided Reflection Journal → https://amzn.to/4reFQSB | 😴 Sleep Support Supplement → https://amzn.to/46FciGe | 💪 Men\'s Health & Recovery Stack → https://amzn.to/40K9J29',
    status: 'Published',
  },
  {
    videoNumber: 9,
    show: 'Life Between Titles',
    season: 1,
    episode: 9,
    guest: 'Savan Kong',
    youtubeTitle: 'If Your Title Disappeared Tomorrow, Who Would You Be?',
    description: 'This one is a question as much as an episode. When the title goes away, most people scramble to replace it. Savan sits with it instead. What\'s underneath the thing you\'ve been calling yourself at dinner parties for the last decade?',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#workidentity',
    resources: '',
    status: 'Published',
  },
  {
    videoNumber: 12,
    show: 'Life Between Titles',
    season: 1,
    episode: 11,
    guest: 'Vanessa Okoro',
    youtubeTitle: 'Representation Has a Price: One Woman\'s Breaking Point',
    description: 'Vanessa Okoro spent over a decade at Ernst & Young climbing from consultant to senior manager before walking away to join the FAA as a federal employee. Then the federal government changed overnight, and she found herself navigating unemployment and a career pivot for the second time in two years. A first-generation Nigerian-American who grew up in New Jersey never quite fitting in — this one is about belonging, burnout as disconnection, and the ego work of job searching after senior leadership.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#federalworker',
    resources: '📄 Teal AI résumé tool → https://get.tealhq.com/zzNxQ7 | 🧠 Free anxiety assessment → https://go.online-therapy.com/SHwO | 📓 Guided Reflection Journal → https://amzn.to/4reFQSB | 😴 Sleep Support Supplement → https://amzn.to/46FciGe | 💪 Men\'s Health & Recovery Stack → https://amzn.to/40K9J29',
    status: 'Published',
  },
  {
    videoNumber: 17,
    show: 'Office Hours',
    season: 1,
    episode: 4,
    guest: 'Cheryl Dillon',
    youtubeTitle: 'The Moment She Stopped Running from Hard Things',
    description: 'Cheryl Dillon has spent her career helping people through the hard parts. In this conversation she shares what she\'s learned from years of guiding others through transition: challenge is not the obstacle. It\'s the mechanism. The people who move forward are the ones who learn to stop running from difficulty and start working with it.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #officehours',
    tags: '#resilience',
    resources: '',
    status: 'Published',
  },
  {
    videoNumber: 18,
    show: 'Life Between Titles',
    season: 1,
    episode: 14,
    guest: 'Savan Kong',
    youtubeTitle: 'The One Thing Nobody Tells You About Starting Over',
    description: 'Two months in. Savan looks back at the guests who shaped the first stretch of Life Between Titles and shares what he didn\'t expect to find in the conversations. Not a recap. A reflection on what uncertainty actually offers when you stop trying to outrun it.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#uncertainty',
    resources: '',
    status: 'Published',
  },
  {
    videoNumber: 27,
    show: 'Life Between Titles',
    season: 1,
    episode: 21,
    guest: 'Savan Kong',
    youtubeTitle: 'The Pattern Behind Every Successful Career Change',
    description: 'A transparent update on where Life Between Titles stands after 25+ conversations. Savan shares what he\'s learned, introduces the new Work, Unscripted series, and talks about the pattern he keeps seeing across every guest who has actually made it through a career change.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#workidentity',
    resources: 'Online Therapy → https://go.online-therapy.com/SHwO',
    status: 'Published',
  },
  {
    videoNumber: 32,
    show: 'Work Unscripted',
    season: 1,
    episode: 6,
    guest: 'David Mazzeo',
    youtubeTitle: 'From the Stage to the Classroom: Why He Gave Up the Mic',
    description: 'David Mazzeo built a career on stages. Emceeing events, holding rooms, reading crowds. Then he walked into a high school and didn\'t leave. This is the Work Unscripted story of how a performer became an alumni director at O\'Dea High School, and what he found in that room that the stage couldn\'t give him.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#emcee',
    resources: '',
    status: 'Published',
  },
  {
    videoNumber: 35,
    show: 'Work Unscripted',
    season: 2,
    episode: 2,
    guest: 'Jordan Swanson',
    youtubeTitle: 'He Rebuilds Children\'s Faces. The Operating Room Is Just the Beginning.',
    description: 'Jordan Swanson is a pediatric craniofacial surgeon at the Children\'s Hospital of Philadelphia, rebuilding the skulls and faces of children born with conditions that affect how they grow, breathe, and move through the world. This conversation is about the craft, the training, the impossible decisions in foreign operating rooms, and the heart that has to go into work this precise.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#pediatricsurgery',
    resources: '',
    status: 'Published',
  },
  {
    videoNumber: 40,
    show: 'Work Unscripted',
    season: 2,
    episode: 6,
    guest: 'Gladdys Uribe',
    youtubeTitle: 'Her Parents Were Undocumented. She Became an Immigration Attorney.',
    description: 'Gladdys Uribe doesn\'t describe herself by her job title. She describes herself as the proud daughter of Mexican immigrants, some of whom were undocumented. She decided at 16 that she would become a civil rights attorney, and she has never once changed her mind. Now she\'s an immigration attorney navigating one of the most consequential moments in the history of her field.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#immigrationlaw',
    resources: '',
    status: 'Published',
  },
  {
    videoNumber: 41,
    show: 'Work Unscripted',
    season: 2,
    episode: 7,
    guest: 'John Sherman',
    youtubeTitle: 'John Interview',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Published',
  },
  {
    videoNumber: 42,
    show: 'Work Unscripted',
    season: 2,
    episode: 8,
    guest: 'Anthony Dyer',
    youtubeTitle: 'Anthony Interview Title',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Published',
  },
  {
    videoNumber: 43,
    show: 'Work Unscripted',
    season: 2,
    episode: 9,
    guest: 'Brett Cohen',
    youtubeTitle: 'He Booked Kim Kardashian From His Mom\'s Phone at 15. Then He Went Viral.',
    description: 'Brett Cohen started an internet radio show at 15 from his bedroom in Long Island on his mom\'s landline phone. By the time he was booking Kim Kardashian, Paris Hilton, and Jimmy Fallon, he was still in high school. Nobody knew. Then in 2012, near 30 Rock, he spent $40 on Craigslist actors, hired fake bodyguards, and walked through Times Square as a nobody. By Friday morning he was on Good Morning America and being interviewed by Lester Holt on the Today Show plaza.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#viralvideo',
    resources: '',
    status: 'Scheduled',
  },
  {
    videoNumber: 44,
    show: 'Work Unscripted',
    season: 2,
    episode: 10,
    guest: 'Alan Levy',
    youtubeTitle: 'Alan\'s Interview',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Scheduled',
  },
  {
    videoNumber: 45,
    show: 'Work Unscripted',
    season: 2,
    episode: 11,
    guest: 'Aaron Dossey',
    youtubeTitle: 'The Scientist Who Bet His Career on Bugs. 14 Years Later, He Was Right.',
    description: 'Aaron Dossey grew up in Oklahoma catching insects in his grandparents\' garden. He got a PhD expecting to become a professor. The faculty jobs had disappeared. So he applied for a Gates Foundation grant in 2011 to research insect protein for human consumption, was told they couldn\'t give money to an individual, and started a company on the spot so he could legally receive it. For 14 years he was the first company in the Western Hemisphere doing serious insect protein research. The world is catching up.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#insectprotein',
    resources: '',
    status: 'Recorded',
  },
  {
    videoNumber: 46,
    show: 'Work Unscripted',
    season: 2,
    episode: 12,
    guest: 'Wayne Wallis',
    youtubeTitle: 'Wayne Interview',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Recorded',
  },
  {
    videoNumber: 47,
    show: 'Work Unscripted',
    season: 2,
    episode: 13,
    guest: 'Kelli Martin',
    youtubeTitle: 'Kelli\'s interview',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Recorded',
  },
  {
    videoNumber: 48,
    show: 'Work Unscripted',
    season: 2,
    episode: 14,
    guest: 'Katie Savage',
    youtubeTitle: 'She Started as CIO of Maryland 8 Months Pregnant. Here\'s What She Built.',
    description: 'Katie Savage took the CIO job for the state of Maryland eight months pregnant. She came from Defense Digital Service, where she learned that the most important thing any technology organization can do is build in-house expertise rather than outsource its thinking to vendors. In Maryland, she found a team that managed contracts. She built a different kind of team.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#womenleadership',
    resources: '',
    status: 'Recorded',
  },
  {
    videoNumber: 50,
    show: 'Work Unscripted',
    season: 2,
    episode: 16,
    guest: 'Shane Jewel',
    youtubeTitle: 'Shane Interview',
    description: '',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '',
    resources: '',
    status: 'Recorded',
  },
  {
    videoNumber: 51,
    show: 'Life Between Titles',
    season: 2,
    episode: 2,
    guest: 'Brett Luartes',
    youtubeTitle: 'He Lost His Job at the Pentagon. He Moved to Mexico. No Regrets.',
    description: 'Brett Luartes spent three and a half years at the Pentagon\'s Defense Digital Service, then watched it get folded into CDAO and slowly lose its purpose. When a miscommunication about working remotely from Mexico cost him his job, he and his wife Danielle didn\'t scramble for the next thing. They ran the numbers, cut their expenses, and moved permanently to Ajijic, a town outside Guadalajara at 5,000 feet elevation. Now Brett walks to the market every morning and is rethinking everything he was told a career was supposed to be.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#retirementabroad',
    resources: 'Teal AI résumé tool → https://get.tealhq.com/zzNxQ7 | Online-Therapy → https://go.online-therapy.com/SHwO | Guided Reflection Journal → https://amzn.to/4reFQSB',
    status: 'Recorded',
  },
  {
    videoNumber: 53,
    show: 'Life Between Titles',
    season: 2,
    episode: 4,
    guest: 'Rory Martin',
    youtubeTitle: 'AI Could Have Ended His 30-Year Career. Instead, He Used It to Start Over at 50.',
    description: 'Rory Martin has been building websites since 1996, teaching himself from used coding manuals before WordPress existed, and grew RoryMartin.com into a marketing agency in 2008. Sixteen years sober, he shares the fear-list exercise he uses to coach people through career changes, and explains why building a $40,000 website in 12 hours with AI scared him into starting Hustle 50, a new venture for anyone over 50 worried AI is coming for their job.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#sobriety #aitools #sidehustle',
    resources: 'Teal AI Resume Tool → https://get.tealhq.com/zzNxQ7 | Online-Therapy Anxiety Assessment → https://go.online-therapy.com/SHwO | Guided Reflection Journal → https://amzn.to/4reFQSB',
    status: 'Recorded',
  },
  {
    videoNumber: 54,
    show: 'Life Between Titles',
    season: 2,
    episode: 5,
    guest: 'David Aviles',
    youtubeTitle: 'He Got Fired Months Before His Startup Hit a $500 Million Valuation. So He Started His Own.',
    description: 'David Aviles spent his career in early-stage tech sales at Optimizely, Amplitude, and Mintlify, and got fired twice — both times just before the company he\'d left took off. He hiked alone into the Marin Headlands to decide what came next, and chose to bet on himself again. Conversations with contractors working on his mother\'s house became the idea for the company he\'s building now, for the trades industry his own brother works in.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#startups #techsales #entrepreneurship',
    resources: 'Teal AI Resume Tool → https://get.tealhq.com/zzNxQ7 | Online-Therapy Anxiety Assessment → https://go.online-therapy.com/SHwO | Guided Reflection Journal → https://amzn.to/4reFQSB',
    status: 'Recorded',
  },
  {
    videoNumber: 55,
    show: 'Life Between Titles',
    season: 2,
    episode: 6,
    guest: 'Cat Gaa',
    youtubeTitle: 'She Moved Abroad at 22 With No Plan. Two Decades and Four Countries Later, She\'s Still Looking for Home.',
    description: 'Cat Gaa left Chicago for Spain at 22 with two suitcases and a Rubbermaid bin of sorority t-shirts, planning to stay one year. Eighteen years, a Spanish husband, and two kids later, she\'s calling in from Riyadh, Saudi Arabia, reckoning with grief, identity, and the question of where home actually is.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#expatlife #motherhood #grief',
    resources: 'Teal AI Resume → https://get.tealhq.com/zzNxQ7 | Online-Therapy → https://go.online-therapy.com/SHwO | Reflection Journal → https://amzn.to/4reFQSB',
    status: 'Recorded',
  },
  {
    videoNumber: 56,
    show: 'Life Between Titles',
    season: 2,
    episode: 7,
    guest: 'Angela Kerek',
    youtubeTitle: 'She Was Ranked 140th in the World at 24. Then She Became a Lawyer. Then She Walked Away From That Too.',
    description: 'Dr. Angela Kerek was ranked 140th in the world as a professional tennis player before retiring at 24. She rebuilt her life as a lawyer in Germany despite not speaking the language, made partner at a top firm after a decade of commuting between Frankfurt and Berlin, then walked away to build a coaching business. She co-wrote the book Winning Inside and talks about the difference between winning outside (titles, rankings, trophies) and winning inside — a compass nobody else can see.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#professionalathlete #burnout #reinvention #midlife',
    resources: 'Teal AI Resume Tool → https://get.tealhq.com/zzNxQ7 | Online-Therapy Anxiety Assessment → https://go.online-therapy.com/SHwO | Guided Reflection Journal → https://amzn.to/4reFQSB',
    status: 'Recorded',
  },
  {
    show: 'Work Unscripted',
    season: 2,
    guest: 'David Murphy',
    youtubeTitle: 'He Took an Acting Class to Impress a Girl. Now He Books National Commercials.',
    description: 'David Murphy took Theater 101 in college to impress a girl named Sophie. His professor watched him do a scene, pulled him aside, and told him he had something. Within four months he booked his first national commercial without knowing what he was supposed to do at an audition. He\'s been at it ever since, living in LA on gig money, going to Bali for three months at a time, and building a life entirely on his own terms.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#comedylife',
    resources: '',
    status: 'Scheduled',
  },
  {
    show: 'Work Unscripted',
    season: 2,
    guest: 'Loung Ung',
    youtubeTitle: 'Loung Interview',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Scheduled',
  },
]

export const PUBLISHED = EPISODES.filter(e => e.status === 'Published')
export const BY_SHOW = (show: Show) => EPISODES.filter(e => e.show === show)
