export type Show = 'Life Between Titles' | 'Work Unscripted' | 'Office Hours'

export interface Episode {
  slug: string
  videoNumber?: number
  show: Show
  season: number
  episode?: number
  guest: string
  youtubeTitle: string
  description: string
  mainTags: string
  tags: string
  resources: string
  status: 'Published' | 'Recorded' | 'Scheduled' | 'Reached Out' | 'To Be Planned'
  photo: string
  youtubeUrl?: string
}

const CDN = 'https://images.squarespace-cdn.com/content/v1/69c8615fa7974634a3112367'

export const EPISODES: Episode[] = [
  // ── Work Unscripted S1 ────────────────────────────────────────
  {
    slug: 'aaron-brooks-federal-prison-food-supervisor',
    videoNumber: undefined,
    show: 'Work Unscripted',
    season: 1,
    episode: 1,
    guest: 'Aaron Brooks',
    youtubeTitle: 'Aaron Brooks, Federal Bureau of Prisons Food Service Supervisor',
    description: 'What does it take to run a kitchen inside a federal prison? Aaron Brooks explains how he built a career feeding people in some of America\'s most controlled environments, from submarine baker to maximum-security institution manager.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#federalprisons #foodservice #military',
    resources: '',
    status: 'Published',
    photo: `${CDN}/9c5162ff-1d99-4730-bfd5-ea78948c8a21/IMG_5986.jpeg`,
  },
  {
    slug: 'andy-alvarado-booking-com-content-creator',
    videoNumber: undefined,
    show: 'Work Unscripted',
    season: 1,
    episode: 2,
    guest: 'Andy Alvarado',
    youtubeTitle: 'Left Booking.com to Build a One-Man Empire: Here\'s How He Did It',
    description: 'Andy Alvarado left his position at Booking.com, relocated his family to rural Oregon, and established a six-figure content creation venture using only a smartphone and embracing imperfection.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#contentcreation #entrepreneurship #remotelife',
    resources: '',
    status: 'Published',
    photo: `${CDN}/83e1dbcf-baf4-49b8-a1a5-e2942e141230/andy-solo2.jpg`,
    youtubeUrl: 'https://youtu.be/LE80aAGh7Jo',
  },
  {
    slug: 'david-mazzeo-emcee-odea',
    videoNumber: 32,
    show: 'Work Unscripted',
    season: 1,
    episode: 6,
    guest: 'David Mazzeo',
    youtubeTitle: 'From the Stage to the Classroom: Why He Gave Up the Mic',
    description: 'David Mazzeo built a career on stages. Emceeing events, holding rooms, reading crowds. Then he walked into a high school and didn\'t leave. This is the Work Unscripted story of how a performer became an alumni director at O\'Dea High School, and what he found in that room that the stage couldn\'t give him.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#emcee #seattlehiphop #mentoring',
    resources: '',
    status: 'Published',
    photo: `${CDN}/7d4c7999-6b47-4aef-897e-087f10deeacc/IMG_8366.jpeg`,
    youtubeUrl: 'https://youtu.be/LpJ0p-HIoeE',
  },
  // ── Life Between Titles S1 ────────────────────────────────────
  {
    slug: 'phil-reiman-pentagon-dod-lawyer',
    videoNumber: 5,
    show: 'Life Between Titles',
    season: 1,
    episode: 5,
    guest: 'Phil Reiman',
    youtubeTitle: '25 Years Inside the Pentagon. Now What?',
    description: 'He spent 25 years inside the Department of Defense as a lawyer. He loved every minute of it. Now he\'s in the in-between, figuring out what a career that long leaves behind and what it points toward. A conversation about the weight of expertise, the strangeness of stopping, and what comes next when the thing that defined you is done.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#governmentcareer #dod #pentagon',
    resources: 'Teal AI résumé tool → https://get.tealhq.com/zzNxQ7 | Free anxiety assessment → https://go.online-therapy.com/SHwO | Guided Reflection Journal → https://amzn.to/4reFQSB',
    status: 'Published',
    photo: '',
  },
  {
    slug: 'savan-kong-title-identity',
    videoNumber: 9,
    show: 'Life Between Titles',
    season: 1,
    episode: 9,
    guest: 'Savan Kong',
    youtubeTitle: 'If Your Title Disappeared Tomorrow, Who Would You Be?',
    description: 'When the title goes away, most people scramble to replace it. Savan sits with it instead. What\'s underneath the thing you\'ve been calling yourself at dinner parties for the last decade?',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#workidentity #soloshow',
    resources: '',
    status: 'Published',
    photo: `${CDN}/ca15d266-eeb0-4750-8266-828ab73926ab/savan-thumb.png`,
  },
  {
    slug: 'vanessa-okoro-ey-faa-reinvention',
    videoNumber: 12,
    show: 'Life Between Titles',
    season: 1,
    episode: 11,
    guest: 'Vanessa Okoro',
    youtubeTitle: 'Representation Has a Price: One Woman\'s Breaking Point',
    description: 'Vanessa Okoro spent over a decade at Ernst & Young climbing from consultant to senior manager before walking away to join the FAA as a federal employee. Then the federal government changed overnight and she found herself navigating unemployment for the second time in two years. A first-generation Nigerian-American story about belonging, burnout as disconnection, and the ego work of job searching after senior leadership.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#federalworker #consulting #firstgen',
    resources: 'Teal AI résumé tool → https://get.tealhq.com/zzNxQ7 | Free anxiety assessment → https://go.online-therapy.com/SHwO',
    status: 'Published',
    photo: '',
  },
  {
    slug: 'savan-kong-starting-over',
    videoNumber: 18,
    show: 'Life Between Titles',
    season: 1,
    episode: 14,
    guest: 'Savan Kong',
    youtubeTitle: 'The One Thing Nobody Tells You About Starting Over',
    description: 'Two months in. Savan looks back at the guests who shaped the first stretch of Life Between Titles and shares what he didn\'t expect to find in the conversations. Not a recap. A reflection on what uncertainty actually offers when you stop trying to outrun it.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#uncertainty #soloshow',
    resources: '',
    status: 'Published',
    photo: `${CDN}/ca15d266-eeb0-4750-8266-828ab73926ab/savan-thumb.png`,
  },
  {
    slug: 'savan-kong-career-change-pattern',
    videoNumber: 27,
    show: 'Life Between Titles',
    season: 1,
    episode: 21,
    guest: 'Savan Kong',
    youtubeTitle: 'The Pattern Behind Every Successful Career Change',
    description: 'A transparent update on where Life Between Titles stands after 25+ conversations. Savan shares what he\'s learned, introduces the new Work, Unscripted series, and talks about the pattern he keeps seeing across every guest who has actually made it through a career change.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#workidentity #soloshow',
    resources: 'Online Therapy → https://go.online-therapy.com/SHwO',
    status: 'Published',
    photo: `${CDN}/ca15d266-eeb0-4750-8266-828ab73926ab/savan-thumb.png`,
  },
  // ── Office Hours S1 ───────────────────────────────────────────
  {
    slug: 'cheryl-dillon-career-coach-hard-things',
    videoNumber: 17,
    show: 'Office Hours',
    season: 1,
    episode: 4,
    guest: 'Cheryl Dillon',
    youtubeTitle: 'The Moment She Stopped Running from Hard Things',
    description: 'Cheryl Dillon has spent her career helping people through the hard parts. Challenge is not the obstacle — it\'s the mechanism. The people who move forward are the ones who learn to stop running from difficulty and start working with it.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #officehours',
    tags: '#resilience #careercoaching',
    resources: '',
    status: 'Published',
    photo: '',
  },
  // ── Work Unscripted S2 ────────────────────────────────────────
  {
    slug: 'nate-sexton-pro-disc-golfer',
    videoNumber: undefined,
    show: 'Work Unscripted',
    season: 2,
    episode: 1,
    guest: 'Nate Sexton',
    youtubeTitle: 'Nate Sexton on Going Pro, Sexton Firebird, & Building a Legacy',
    description: 'Professional disc golfer Nate Sexton discusses his 2004 transition to pro status, his signature Sexton Firebird disc, PDGA Sportsmanship Award, and the question of what legacy looks like when a career you love might be winding down.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#discgolf #professionalathlete #legacy',
    resources: '',
    status: 'Published',
    photo: `${CDN}/4a1c09a5-f460-43c4-b747-1a057ac328c3/sean-sinclair-0Y6BaIZeh0g-unsplash.jpg`,
    youtubeUrl: 'https://youtu.be/hdz6RZ1tJX0',
  },
  {
    slug: 'jordan-swanson-pediatric-craniofacial-surgeon',
    videoNumber: 35,
    show: 'Work Unscripted',
    season: 2,
    episode: 2,
    guest: 'Jordan Swanson',
    youtubeTitle: 'He Rebuilds Children\'s Faces. The Operating Room Is Just the Beginning.',
    description: 'Jordan Swanson is a pediatric craniofacial surgeon at the Children\'s Hospital of Philadelphia, rebuilding the skulls and faces of children born with conditions that affect how they grow, breathe, and move through the world. A conversation about craft, training, impossible decisions in foreign operating rooms, and the heart that has to go into work this precise.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#pediatricsurgery #medicine #globalhealth',
    resources: '',
    status: 'Published',
    photo: `${CDN}/ff537cd0-fe70-4b2d-be17-f588b47e625f/BioPhoto-PLA-JordanSwanson-2624x1720.jpeg`,
  },
  {
    slug: 'jerry-glavy-marine-general-cyber-command',
    videoNumber: undefined,
    show: 'Work Unscripted',
    season: 2,
    episode: 3,
    guest: 'Lt. Gen. Matthew "Jerry" Glavy',
    youtubeTitle: 'From Marine One to Cyber Command: 39 Years of Leading Through the Invisible',
    description: 'Lt. Gen. Matthew "Jerry" Glavy flew Marine One, commanded Cyber and Space Operations, and spent 39 years in the U.S. Marine Corps. Now he runs AI Ready Veteran, a 501(c)(3) preparing veterans for the AI workforce. A conversation about leading through what you cannot see, the zero-defect culture of presidential aviation, and what comes after a career defined by service.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#military #cybercommand #leadership #marineone',
    resources: '',
    status: 'Published',
    photo: `${CDN}/747fa92e-0c0a-4cbb-8bd4-1e0012e636ce/Lt._Gen._Matthew_G._Glavy.jpg`,
  },
  {
    slug: 'danielle-frank-wine-spirits-author-reinvention',
    videoNumber: undefined,
    show: 'Work Unscripted',
    season: 2,
    episode: 4,
    guest: 'Danielle Frank',
    youtubeTitle: 'Danielle Frank on Quitting Without a Plan and the Book She Carried for 14 Years',
    description: 'Danielle Frank quit Miramax, walked away from a toxic PR job without a backup plan, built a 22-year wine industry career, ended an engagement, and finally published a rhyming parenting book she had been carrying for 14 years. A story about the pivots most people don\'t put on LinkedIn.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#wineindustry #publishing #parenting #reinvention',
    resources: '',
    status: 'Published',
    photo: `${CDN}/3827ece1-ee90-4f55-a9cc-6bcf32bb16f6/9+26+25DanielleFrank_%40TRosePhotos-22.jpg`,
  },
  {
    slug: 'gladdys-uribe-immigration-attorney',
    videoNumber: 40,
    show: 'Work Unscripted',
    season: 2,
    episode: 6,
    guest: 'Gladdys Uribe',
    youtubeTitle: 'Her Parents Were Undocumented. She Became an Immigration Attorney.',
    description: 'Gladdys Uribe describes herself as the proud daughter of Mexican immigrants, some of whom were undocumented. She decided at 16 that she would become a civil rights attorney and has never once changed her mind. Now she practices immigration law during one of the most consequential moments in the history of her field.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#immigrationlaw #civilrights #firstgen',
    resources: '',
    status: 'Published',
    photo: '',
  },
  {
    slug: 'john-sherman-work-unscripted',
    videoNumber: 41,
    show: 'Work Unscripted',
    season: 2,
    episode: 7,
    guest: 'John Sherman',
    youtubeTitle: 'John Sherman',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Published',
    photo: '',
  },
  {
    slug: 'anthony-dyer-work-unscripted',
    videoNumber: 42,
    show: 'Work Unscripted',
    season: 2,
    episode: 8,
    guest: 'Anthony Dyer',
    youtubeTitle: 'Anthony Dyer',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Published',
    photo: '',
  },
  {
    slug: 'brett-cohen-viral-radio-times-square',
    videoNumber: 43,
    show: 'Work Unscripted',
    season: 2,
    episode: 9,
    guest: 'Brett Cohen',
    youtubeTitle: 'He Booked Kim Kardashian From His Mom\'s Phone at 15. Then He Went Viral.',
    description: 'Brett Cohen started an internet radio show at 15 from his bedroom in Long Island on his mom\'s landline phone. By the time he was booking Kim Kardashian, Paris Hilton, and Jimmy Fallon, he was still in high school. Then a $40 Craigslist stunt in Times Square landed him on Good Morning America and the Today Show by Friday morning.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#viralvideo #media #radio',
    resources: '',
    status: 'Scheduled',
    photo: '',
  },
  {
    slug: 'alan-levy-work-unscripted',
    videoNumber: 44,
    show: 'Work Unscripted',
    season: 2,
    episode: 10,
    guest: 'Alan Levy',
    youtubeTitle: 'Alan Levy',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Scheduled',
    photo: '',
  },
  {
    slug: 'aaron-dossey-insect-protein-scientist',
    videoNumber: 45,
    show: 'Work Unscripted',
    season: 2,
    episode: 11,
    guest: 'Aaron Dossey',
    youtubeTitle: 'The Scientist Who Bet His Career on Bugs. 14 Years Later, He Was Right.',
    description: 'Aaron Dossey got a PhD expecting to become a professor. The faculty jobs had disappeared. So he applied for a Gates Foundation grant in 2011 to research insect protein for human consumption, was told they couldn\'t give money to an individual, and started a company on the spot. For 14 years he was the first company in the Western Hemisphere doing serious insect protein research. The world is catching up.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#insectprotein #science #entrepreneurship',
    resources: '',
    status: 'Recorded',
    photo: '',
  },
  {
    slug: 'wayne-wallis-work-unscripted',
    videoNumber: 46,
    show: 'Work Unscripted',
    season: 2,
    episode: 12,
    guest: 'Wayne Wallis',
    youtubeTitle: 'Wayne Wallis',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Recorded',
    photo: '',
  },
  {
    slug: 'kelli-martin-work-unscripted',
    videoNumber: 47,
    show: 'Work Unscripted',
    season: 2,
    episode: 13,
    guest: 'Kelli Martin',
    youtubeTitle: 'Kelli Martin',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Recorded',
    photo: '',
  },
  {
    slug: 'katie-savage-cio-maryland',
    videoNumber: 48,
    show: 'Work Unscripted',
    season: 2,
    episode: 14,
    guest: 'Katie Savage',
    youtubeTitle: 'She Started as CIO of Maryland 8 Months Pregnant. Here\'s What She Built.',
    description: 'Katie Savage took the CIO job for the state of Maryland eight months pregnant. She came from Defense Digital Service, where she learned that the most important thing any technology organization can do is build in-house expertise rather than outsource its thinking to vendors. In Maryland, she found a team that managed contracts. She built a different kind of team.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#womenleadership #govtech #cio',
    resources: '',
    status: 'Recorded',
    photo: '',
  },
  {
    slug: 'shane-jewel-work-unscripted',
    videoNumber: 50,
    show: 'Work Unscripted',
    season: 2,
    episode: 16,
    guest: 'Shane Jewel',
    youtubeTitle: 'Shane Jewel',
    description: '',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '',
    resources: '',
    status: 'Recorded',
    photo: '',
  },
  // ── Life Between Titles S2 ────────────────────────────────────
  {
    slug: 'brett-luartes-pentagon-early-retirement-mexico',
    videoNumber: 51,
    show: 'Life Between Titles',
    season: 2,
    episode: 2,
    guest: 'Brett Luartes',
    youtubeTitle: 'He Lost His Job at the Pentagon. He Moved to Mexico. No Regrets.',
    description: 'Brett Luartes spent three and a half years at the Pentagon\'s Defense Digital Service, then watched it get folded into CDAO and slowly lose its purpose. When a miscommunication about working remotely from Mexico cost him his job, he and his wife Danielle moved permanently to Ajijic — a town outside Guadalajara at 5,000 feet elevation. He\'s rethinking everything he was told a career was supposed to be.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#retirementabroad #pentagon #earlyretirement',
    resources: 'Teal AI résumé tool → https://get.tealhq.com/zzNxQ7 | Online-Therapy → https://go.online-therapy.com/SHwO',
    status: 'Recorded',
    photo: '',
  },
  {
    slug: 'rory-martin-ai-hustle-50-sobriety',
    videoNumber: 53,
    show: 'Life Between Titles',
    season: 2,
    episode: 4,
    guest: 'Rory Martin',
    youtubeTitle: 'AI Could Have Ended His 30-Year Career. Instead, He Used It to Start Over at 50.',
    description: 'Rory Martin has been building websites since 1996, teaching himself from used coding manuals before WordPress existed. Sixteen years sober, he shares the fear-list exercise he uses to coach people through career changes, and explains why building a $40,000 website in 12 hours with AI scared him into starting Hustle 50 — a new venture for anyone over 50 worried AI is coming for their job.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#sobriety #aitools #sidehustle',
    resources: 'Teal AI Resume Tool → https://get.tealhq.com/zzNxQ7 | Online-Therapy → https://go.online-therapy.com/SHwO | Guided Reflection Journal → https://amzn.to/4reFQSB',
    status: 'Recorded',
    photo: '',
  },
  {
    slug: 'david-aviles-tech-sales-fired-startup',
    videoNumber: 54,
    show: 'Life Between Titles',
    season: 2,
    episode: 5,
    guest: 'David Aviles',
    youtubeTitle: 'He Got Fired Months Before His Startup Hit a $500 Million Valuation. So He Started His Own.',
    description: 'David Aviles spent his career in early-stage tech sales at Optimizely, Amplitude, and Mintlify, and got fired twice — both times just before the company he\'d left took off. He hiked alone into the Marin Headlands to decide what came next, chose to bet on himself again, and is now building a company for the trades industry after conversations with contractors working on his mother\'s house sparked the idea.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#startups #techsales #entrepreneurship',
    resources: 'Teal AI Resume Tool → https://get.tealhq.com/zzNxQ7 | Online-Therapy → https://go.online-therapy.com/SHwO',
    status: 'Recorded',
    photo: '',
  },
  {
    slug: 'cat-gaa-expat-spain-saudi-arabia-home',
    videoNumber: 55,
    show: 'Life Between Titles',
    season: 2,
    episode: 6,
    guest: 'Cat Gaa',
    youtubeTitle: 'She Moved Abroad at 22 With No Plan. Two Decades and Four Countries Later, She\'s Still Looking for Home.',
    description: 'Cat Gaa left Chicago for Spain at 22 with two suitcases, planning to stay one year. Eighteen years, a Spanish husband, and two kids later, she\'s calling in from Riyadh, Saudi Arabia, reckoning with grief, identity, and the question of where home actually is.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#expatlife #motherhood #grief',
    resources: 'Teal AI Resume → https://get.tealhq.com/zzNxQ7 | Online-Therapy → https://go.online-therapy.com/SHwO',
    status: 'Recorded',
    photo: '',
  },
  {
    slug: 'angela-kerek-tennis-lawyer-coach-winning-inside',
    videoNumber: 56,
    show: 'Life Between Titles',
    season: 2,
    episode: 7,
    guest: 'Angela Kerek',
    youtubeTitle: 'She Was Ranked 140th in the World at 24. Then She Became a Lawyer. Then She Walked Away From That Too.',
    description: 'Dr. Angela Kerek was ranked 140th in the world as a professional tennis player before retiring at 24. She rebuilt her life as a lawyer in Germany without speaking the language, made partner at a top firm, then walked away to build a coaching business. Co-author of Winning Inside — on the difference between winning outside (titles, rankings) and winning inside, a compass nobody else can see.',
    mainTags: '#lifebetweentitles #careertransition #identity #lifetransition',
    tags: '#professionalathlete #burnout #reinvention #midlife',
    resources: 'Teal AI Resume Tool → https://get.tealhq.com/zzNxQ7 | Online-Therapy → https://go.online-therapy.com/SHwO',
    status: 'Recorded',
    photo: '',
  },
  // ── Work Unscripted S2 (cont.) ────────────────────────────────
  {
    slug: 'david-murphy-actor-commercial-bali',
    show: 'Work Unscripted',
    season: 2,
    guest: 'David Murphy',
    youtubeTitle: 'He Took an Acting Class to Impress a Girl. Now He Books National Commercials.',
    description: 'David Murphy took Theater 101 in college to impress a girl named Sophie. His professor told him he had something. Within four months he booked his first national commercial without knowing what he was supposed to do at an audition. He\'s been at it ever since — living in LA on gig money, going to Bali for three months at a time, building a life entirely on his own terms.',
    mainTags: '#lifebetweentitles #careertransition #lifetransition #identity #workunscripted',
    tags: '#acting #gigeconomy #bali',
    resources: '',
    status: 'Scheduled',
    photo: '',
  },
  {
    slug: 'loung-ung-work-unscripted',
    show: 'Work Unscripted',
    season: 2,
    guest: 'Loung Ung',
    youtubeTitle: 'Loung Ung',
    description: '',
    mainTags: '',
    tags: '',
    resources: '',
    status: 'Scheduled',
    photo: '',
  },
]

export const PUBLISHED = EPISODES.filter(e => e.status === 'Published')
export const BY_SHOW = (show: Show) => EPISODES.filter(e => e.show === show)
export const BY_SLUG = (slug: string) => EPISODES.find(e => e.slug === slug)
